import { useState } from 'react';
import { Modal, Button, Form } from 'react-bootstrap';
import './AddNodeModal.css';

const AddNodeModal = ({ show, onHide, onAddNode, nodes }) => {
  const [question, setQuestion] = useState('');
  const [answer, setAnswer] = useState('');
  const [parentId, setParentId] = useState('');

  const handleSubmit = (e) => {
    e.preventDefault();
    if (question.trim() && answer.trim() && parentId) {
      onAddNode({
        question: question.trim(),
        answer: answer.trim(),
        parentId
      });
      // Reset form
      setQuestion('');
      setAnswer('');
      setParentId('');
      onHide();
    }
  };

  const handleClose = () => {
    setQuestion('');
    setAnswer('');
    setParentId('');
    onHide();
  };

  return (
    <Modal show={show} onHide={handleClose} size="lg" centered>
      <Modal.Header closeButton className="add-node-modal-header">
        <Modal.Title>
          <svg
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            style={{ marginRight: '0.5rem' }}
          >
            <circle cx="12" cy="12" r="10" />
            <line x1="12" y1="8" x2="12" y2="16" />
            <line x1="8" y1="12" x2="16" y2="12" />
          </svg>
          Add New Question Node
        </Modal.Title>
      </Modal.Header>
      <Form onSubmit={handleSubmit}>
        <Modal.Body>
          <Form.Group className="mb-3">
            <Form.Label className="add-node-label">
              <svg
                width="18"
                height="18"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <circle cx="12" cy="12" r="10" />
                <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3" />
                <line x1="12" y1="17" x2="12.01" y2="17" />
              </svg>
              Question
            </Form.Label>
            <Form.Control
              as="textarea"
              rows={2}
              placeholder="Enter your question..."
              value={question}
              onChange={(e) => setQuestion(e.target.value)}
              required
            />
          </Form.Group>

          <Form.Group className="mb-3">
            <Form.Label className="add-node-label">
              <svg
                width="18"
                height="18"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" />
              </svg>
              Answer
            </Form.Label>
            <Form.Control
              as="textarea"
              rows={4}
              placeholder="Enter the answer..."
              value={answer}
              onChange={(e) => setAnswer(e.target.value)}
              required
            />
            <Form.Text className="text-muted">
              In the future, this will be automatically generated by the backend.
            </Form.Text>
          </Form.Group>

          <Form.Group className="mb-3">
            <Form.Label className="add-node-label">
              <svg
                width="18"
                height="18"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <polyline points="15 18 9 12 15 6" />
              </svg>
              Parent Node
            </Form.Label>
            <Form.Select
              value={parentId}
              onChange={(e) => setParentId(e.target.value)}
              required
            >
              <option value="">Select a parent node...</option>
              {nodes.map((node) => (
                <option key={node.id} value={node.id}>
                  {node.data.question}
                </option>
              ))}
            </Form.Select>
            <Form.Text className="text-muted">
              The new node will be connected to this parent node.
            </Form.Text>
          </Form.Group>
        </Modal.Body>
        <Modal.Footer>
          <Button variant="secondary" onClick={handleClose}>
            Cancel
          </Button>
          <Button
            variant="primary"
            type="submit"
            disabled={!question.trim() || !answer.trim() || !parentId}
          >
            <svg
              width="18"
              height="18"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
              style={{ marginRight: '0.5rem' }}
            >
              <circle cx="12" cy="12" r="10" />
              <line x1="12" y1="8" x2="12" y2="16" />
              <line x1="8" y1="12" x2="16" y2="12" />
            </svg>
            Add Node
          </Button>
        </Modal.Footer>
      </Form>
    </Modal>
  );
};

export default AddNodeModal;
